# Generated by Django 3.0.6 on 2020-05-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300, unique=True)),
                ('summary', models.TextField(max_length=1000)),
                ('image_url', models.URLField(blank=True)),
                ('author', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
