language: python
python:
- '3.6'
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
- pip3 install -r requirements.txt
- psql -c 'create database news;' -U postgres
- python manage.py makemigrations
- python manage.py migrate
script:
- python manage.py test
